// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.5
// source: gochat.proto

package proto

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GoChatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *GoChatRequest) Reset() {
	*x = GoChatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gochat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoChatRequest) ProtoMessage() {}

func (x *GoChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gochat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoChatRequest.ProtoReflect.Descriptor instead.
func (*GoChatRequest) Descriptor() ([]byte, []int) {
	return file_gochat_proto_rawDescGZIP(), []int{0}
}

func (x *GoChatRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GoChatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *GoChatResponse) Reset() {
	*x = GoChatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gochat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoChatResponse) ProtoMessage() {}

func (x *GoChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gochat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoChatResponse.ProtoReflect.Descriptor instead.
func (*GoChatResponse) Descriptor() ([]byte, []int) {
	return file_gochat_proto_rawDescGZIP(), []int{1}
}

func (x *GoChatResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GoChataudioRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg      string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Filename string `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
}

func (x *GoChataudioRequest) Reset() {
	*x = GoChataudioRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gochat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoChataudioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoChataudioRequest) ProtoMessage() {}

func (x *GoChataudioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gochat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoChataudioRequest.ProtoReflect.Descriptor instead.
func (*GoChataudioRequest) Descriptor() ([]byte, []int) {
	return file_gochat_proto_rawDescGZIP(), []int{2}
}

func (x *GoChataudioRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GoChataudioRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type GoChataudioResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg        string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Filelongth int32  `protobuf:"varint,2,opt,name=filelongth,proto3" json:"filelongth,omitempty"`
}

func (x *GoChataudioResponse) Reset() {
	*x = GoChataudioResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gochat_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoChataudioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoChataudioResponse) ProtoMessage() {}

func (x *GoChataudioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gochat_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoChataudioResponse.ProtoReflect.Descriptor instead.
func (*GoChataudioResponse) Descriptor() ([]byte, []int) {
	return file_gochat_proto_rawDescGZIP(), []int{3}
}

func (x *GoChataudioResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GoChataudioResponse) GetFilelongth() int32 {
	if x != nil {
		return x.Filelongth
	}
	return 0
}

var File_gochat_proto protoreflect.FileDescriptor

var file_gochat_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x67, 0x6f, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x67, 0x6f, 0x63, 0x68, 0x61, 0x74, 0x22, 0x21, 0x0a, 0x0d, 0x47, 0x6f, 0x43, 0x68, 0x61, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x22, 0x0a, 0x0e, 0x47, 0x6f, 0x43,
	0x68, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x42, 0x0a,
	0x12, 0x47, 0x6f, 0x43, 0x68, 0x61, 0x74, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x47, 0x0a, 0x13, 0x47, 0x6f, 0x43, 0x68, 0x61, 0x74, 0x61, 0x75, 0x64, 0x69, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x66, 0x69,
	0x6c, 0x65, 0x6c, 0x6f, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x66, 0x69, 0x6c, 0x65, 0x6c, 0x6f, 0x6e, 0x67, 0x74, 0x68, 0x32, 0x90, 0x01, 0x0a, 0x0d, 0x47,
	0x6f, 0x43, 0x68, 0x61, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x37, 0x0a, 0x06,
	0x47, 0x6f, 0x43, 0x68, 0x61, 0x74, 0x12, 0x15, 0x2e, 0x67, 0x6f, 0x63, 0x68, 0x61, 0x74, 0x2e,
	0x47, 0x6f, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x67, 0x6f, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x47, 0x6f, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x0b, 0x47, 0x6f, 0x43, 0x68, 0x61, 0x74, 0x41,
	0x75, 0x64, 0x69, 0x6f, 0x12, 0x1a, 0x2e, 0x67, 0x6f, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x47, 0x6f,
	0x43, 0x68, 0x61, 0x74, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1b, 0x2e, 0x67, 0x6f, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x47, 0x6f, 0x43, 0x68, 0x61, 0x74,
	0x61, 0x75, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0e, 0x5a,
	0x0c, 0x67, 0x6f, 0x63, 0x68, 0x61, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gochat_proto_rawDescOnce sync.Once
	file_gochat_proto_rawDescData = file_gochat_proto_rawDesc
)

func file_gochat_proto_rawDescGZIP() []byte {
	file_gochat_proto_rawDescOnce.Do(func() {
		file_gochat_proto_rawDescData = protoimpl.X.CompressGZIP(file_gochat_proto_rawDescData)
	})
	return file_gochat_proto_rawDescData
}

var file_gochat_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_gochat_proto_goTypes = []interface{}{
	(*GoChatRequest)(nil),       // 0: gochat.GoChatRequest
	(*GoChatResponse)(nil),      // 1: gochat.GoChatResponse
	(*GoChataudioRequest)(nil),  // 2: gochat.GoChataudioRequest
	(*GoChataudioResponse)(nil), // 3: gochat.GoChataudioResponse
}
var file_gochat_proto_depIdxs = []int32{
	0, // 0: gochat.GoChatService.GoChat:input_type -> gochat.GoChatRequest
	2, // 1: gochat.GoChatService.GoChatAudio:input_type -> gochat.GoChataudioRequest
	1, // 2: gochat.GoChatService.GoChat:output_type -> gochat.GoChatResponse
	3, // 3: gochat.GoChatService.GoChatAudio:output_type -> gochat.GoChataudioResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gochat_proto_init() }
func file_gochat_proto_init() {
	if File_gochat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gochat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoChatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gochat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoChatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gochat_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoChataudioRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gochat_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoChataudioResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gochat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gochat_proto_goTypes,
		DependencyIndexes: file_gochat_proto_depIdxs,
		MessageInfos:      file_gochat_proto_msgTypes,
	}.Build()
	File_gochat_proto = out.File
	file_gochat_proto_rawDesc = nil
	file_gochat_proto_goTypes = nil
	file_gochat_proto_depIdxs = nil
}
