/*
   get https://live.kuaishou.com/live_api/emoji/allgifts
*/

package ksgift

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"net/http"
)

type Gift struct {
	GiftName string `json:"giftName"`
	GiftURL  string `json:"giftUrl"`
}

type AutoGenerated struct {
	Data map[string]Gift `json:"data"` // 礼物ID: 礼物信息
}

func Ksgift() (*AutoGenerated, error) {
	giftdata := &AutoGenerated{}

	err := getData(giftdata)
	if err != nil {
		fmt.Println("获取数据失败:", err)
		return nil, err
	}
	return giftdata, nil
	// printGifts(giftdata)
}

func getData(data *AutoGenerated) error {
	// 发送GET请求
	resp, err := http.Get("https://live.kuaishou.com/live_api/emoji/allgifts")
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	// 读取响应的内容
	body, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		return err
	}

	// 解析JSON数据
	err = json.Unmarshal(body, data)
	if err != nil {
		return err
	}

	return nil
}

func printGifts(data *AutoGenerated) {
	// 打印礼物信息
	for key, gift := range data.Data {
		fmt.Printf("礼物ID: %s\n礼物名称: %s\n礼物URL: %s\n\n", key, gift.GiftName, gift.GiftURL)
	}
}
